export interface Sweep {

}


// THIS SHIT WORKS BUT ITS WEIRD AND COMPLICATED, MAYBE START FROM SCRATCH AND TAKE INSPIRATION FROM THE OTHER GUY, CREATE NEW INTERFACE 
// THAT WORKS FOR BOTH SWEEP AND REVOLUTION AND THEY ADAPT TO THE GEOMETRY INTERFACE, SO BASICALLY DO THE LEVEL MATRIX SHIT AND RETURN THE BUFFERS.
// RECEIVE A SHAPE CURVE, RECEIVE A SHAPE PATH, DO WHATEVER YOU NEED, BUT HAVE A METHOD THAT RETURNS THE THE BUFFERS ENTIRELY. 


// POSSIBLE HIERARCHY.
// SWEEPEABLE < ---IMPLEMENTS--- (PATH,REVOLUTION).
// PATH RECEIVES A SHAPE CURVE AND PATH CURVE, REVOLUTION JUST THE SHAPE CURVE.
// INTERFACE SHOULD PROVIDE GET FILL BUFFERS METHOD. SO IF A GEOMETRY OBJECT USES THIS IT CAN CALL THAT BUT STILL USE THE DEFAULT INDEX BUFFER METHOD.


// https://github.com/imontecalvo/TP-Sistemas-Graficos/blob/main/superficieBarrido.js